### ISSUE TITLE
using with generators

### ISSUE THREAD

**Issue by fend25** [lourenzo/postgres-bluebird#3]
Hi. Nice module, thank you.
My question: how should I use pg-bluebird with generators?
Using this is too ugly for me (I think, it's nothing better than named callbacks):

``` js
pg.connectAsync(...).spread(function(connection, release) {
     return connection.queryAsync("...")
         .then(function(result) {
            console.log("rows", result.rows);
         })
         .finally(function() {
            release();
         });
});
```

I prefer something like this,  but I can't write it correctly:

``` js
var conn = yield pg.connectAsync(connString);
var res = yield conn.queryAsync('SELECT now();');
console.log(res); //current time from db
```

**Comment by lourenzo** [comment]
Well, the `yield` syntax surely looks better, but it's a es6 feature that requires running node with special flags ( `--harmony` ), so it's still not as simple as it seems.

But if you think of a better implementation and some improved way to do it, feel free to contact me.

Regards,
Lourenzo
